"""
dpo.py
======
Stage 5b: Direct Preference Optimization on questions scoring < 0.5.

Workflow:
  1. Load eval results to identify weak questions (score < DPO_THRESHOLD).
  2. Use seeds.jsonl to find existing answers for those question types.
  3. Generate "rejected" answers using the base model (wrong / incomplete).
  4. Use "chosen" answers from seeds (high-quality with citations).
  5. Run DPO via Unsloth/TRL on (chosen, rejected) pairs.
  6. Save DPO-tuned adapter to outputs/atp-gemma4-31b-dpo/

CRITICAL:
  - NEVER fp16 — Gemma 4 activations overflow fp16. Always bf16.
  - Read base model path from adapter_config.json, never hardcode.
  - Stop Ollama before running (VRAM conflict).
  - Only applies DPO to the SFT adapter, not the base model directly.

Usage:
    python dpo.py --sft outputs/atp-gemma4-31b-v1 --eval eval/results/v1.json
    python dpo.py --sft outputs/atp-gemma4-31b-v1 --eval eval/results/v1.json --out outputs/atp-gemma4-31b-dpo
    python dpo.py --sft outputs/atp-gemma4-31b-v1 --eval eval/results/v1.json --seeds data/seeds.jsonl
"""

import json
import argparse
import sys
import time
import random
import requests
from pathlib import Path
from typing import Optional

# ── Config ────────────────────────────────────────────────────

OLLAMA_MODEL    = "gemma4:31b"
OLLAMA_URL      = "http://localhost:11434/api/generate"
DPO_THRESHOLD   = 0.5
RANDOM_SEED     = 42
DPO_EPOCHS      = 1
DPO_LR          = 5e-5
DPO_BATCH       = 1
DPO_GRAD_ACCUM  = 4
DPO_BETA        = 0.1       # KL penalty strength
MAX_SEQ_LENGTH  = 4096

EVAL_SYSTEM = (
    "You are a doctrine-grounded military intelligence assistant specializing in "
    "ATP 2-01.3 (Intelligence Preparation of the Battlefield, March 2019). "
    "Place citations at the END in [Reference: ATP 2-01.3, para X-Y] format."
)


# ── Ollama helpers ────────────────────────────────────────────

def coerce_str(val) -> str:
    if isinstance(val, str):   return val
    if isinstance(val, dict):  return json.dumps(val)
    if isinstance(val, list):  return " ".join(str(v) for v in val)
    return str(val)


def generate_rejected(question: str, temperature: float = 0.9) -> Optional[str]:
    """
    Generate a plausible-but-wrong answer for the given question.
    Higher temperature intentionally produces less accurate responses.
    """
    prompt = (
        f"Answer this military intelligence question: {question}\n\n"
        "Give a brief, plausible answer but do not include specific paragraph "
        "citations or detailed doctrinal steps."
    )
    try:
        response = requests.post(
            OLLAMA_URL,
            json={
                "model":  OLLAMA_MODEL,
                "prompt": prompt,
                "system": "You are a general military assistant.",
                "stream": False,
                "options": {
                    "temperature": temperature,
                    "top_k":       64,
                    "top_p":       0.95,
                    "num_predict": 300,
                },
            },
            timeout=120,
        )
        result = response.json()
        return coerce_str(result.get("response", ""))
    except Exception as e:
        print(f"  [dpo] Ollama error generating rejected: {e}")
        return None


# ── Build DPO pairs ───────────────────────────────────────────

def load_eval_results(eval_path: str) -> list[str]:
    """Return list of question IDs that need DPO (score < threshold)."""
    with open(eval_path, encoding='utf-8') as f:
        results = json.load(f)
    dpo_ids = results.get("dpo_ids", [])
    print(f"[dpo] Questions needing DPO: {dpo_ids}")
    return dpo_ids


def load_seeds(seeds_path: str) -> list[dict]:
    seeds = []
    with open(seeds_path, encoding='utf-8') as f:
        for line in f:
            try:
                seeds.append(json.loads(line))
            except Exception:
                pass
    return seeds


def match_seeds_to_question_types(seeds: list[dict], question_types: list[str]) -> list[dict]:
    """Find seeds matching the question types flagged for DPO."""
    matched = [s for s in seeds if s.get("question_type") in question_types]
    print(f"[dpo] Matched {len(matched)} seeds for DPO types: {question_types}")
    return matched


def build_dpo_pairs(
    seeds:       list[dict],
    eval_results: list[str],
    max_pairs:   int = 200,
) -> list[dict]:
    """
    Build (chosen, rejected) pairs for DPO training.
    chosen  = high-quality seed answer with citation
    rejected = shorter, uncited answer generated by Ollama
    """
    # Map eval question IDs to rough question types
    # F-0x => factual, P-0x => procedural, etc.
    type_map = {
        "F":  "factual",
        "P":  "procedural",
        "C":  "comparative",
        "E":  "echelon_specific",
        "AR": "applied_reasoning",
        "PG": "product_generation",
        "CS": "cross_step",
        "MD": "multi_domain",
        "CT": "contrastive",
    }
    target_types = set()
    for qid in eval_results:
        prefix = qid.split("-")[0]
        if prefix in type_map:
            target_types.add(type_map[prefix])

    if not target_types:
        # Fallback: use all seeds
        target_seeds = seeds
    else:
        target_seeds = [s for s in seeds if s.get("question_type") in target_types]

    if not target_seeds:
        print("[dpo] No seeds matched — using all seeds for DPO")
        target_seeds = seeds

    random.seed(RANDOM_SEED)
    random.shuffle(target_seeds)
    target_seeds = target_seeds[:max_pairs]

    pairs = []
    for i, seed in enumerate(target_seeds):
        q       = seed.get("question", "").strip()
        chosen  = seed.get("answer",   "").strip()
        if not q or not chosen:
            continue

        print(f"  [{i+1}/{len(target_seeds)}] Generating rejected for: {q[:60]}...", flush=True)
        rejected = generate_rejected(q)
        if not rejected or len(rejected.split()) < 10:
            rejected = "I don't have specific information about that doctrine."

        pairs.append({
            "prompt":   q,
            "chosen":   chosen,
            "rejected": rejected,
        })

    print(f"[dpo] Built {len(pairs)} DPO pairs")
    return pairs


# ── DPO Training ──────────────────────────────────────────────

def run_dpo(
    sft_adapter: str,
    pairs:       list[dict],
    output_dir:  str,
) -> None:
    try:
        import torch
        from unsloth import FastLanguageModel
        from trl import DPOTrainer, DPOConfig
        from datasets import Dataset
    except ImportError as e:
        print(f"[dpo] Import error: {e}")
        print("[dpo] Activate environment: source ~/caimll_finetuning/bin/activate")
        sys.exit(1)

    # CRITICAL: bf16 only for Gemma 4
    if not torch.cuda.is_bf16_supported():
        print("[dpo] FATAL: bf16 not supported. Gemma 4 requires bf16.")
        sys.exit(1)

    # Read base model from adapter_config.json — NEVER hardcode
    adapter_cfg_path = Path(sft_adapter) / "adapter_config.json"
    if not adapter_cfg_path.exists():
        print(f"[dpo] ERROR: adapter_config.json not found in {sft_adapter}")
        sys.exit(1)
    with open(adapter_cfg_path, encoding='utf-8') as f:
        adapter_cfg = json.load(f)
    base_model_id = adapter_cfg.get("base_model_name_or_path", "unsloth/gemma-4-31B")
    print(f"[dpo] Base model (from adapter_config): {base_model_id}")
    print(f"[dpo] SFT adapter                     : {sft_adapter}")
    print(f"[dpo] DPO pairs                        : {len(pairs)}")
    print(f"[dpo] Output dir                       : {output_dir}")

    # Load SFT adapter as starting point for DPO
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name     = sft_adapter,
        max_seq_length = MAX_SEQ_LENGTH,
        dtype          = None,
        load_in_4bit   = True,
    )

    # Apply LoRA for DPO (same config as SFT)
    model = FastLanguageModel.get_peft_model(
        model,
        r              = 16,
        target_modules = [
            "q_proj", "k_proj", "v_proj", "o_proj",
            "gate_proj", "up_proj", "down_proj",
        ],
        lora_alpha              = 32,
        lora_dropout            = 0.0,
        bias                    = "none",
        use_gradient_checkpointing = "unsloth",
        random_state            = RANDOM_SEED,
        use_rslora              = True,
    )

    # Build dataset — DPOTrainer expects {prompt, chosen, rejected}
    dataset = Dataset.from_list(pairs)
    split   = dataset.train_test_split(test_size=0.1, seed=RANDOM_SEED)

    Path(output_dir).mkdir(parents=True, exist_ok=True)

    start = time.time()

    trainer = DPOTrainer(
        model        = model,
        ref_model    = None,    # use the peft model's base as reference
        tokenizer    = tokenizer,
        train_dataset= split["train"],
        eval_dataset = split["test"],
        args = DPOConfig(
            output_dir                  = output_dir,
            beta                        = DPO_BETA,
            per_device_train_batch_size = DPO_BATCH,
            gradient_accumulation_steps = DPO_GRAD_ACCUM,
            num_train_epochs            = DPO_EPOCHS,
            learning_rate               = DPO_LR,
            lr_scheduler_type           = "cosine",
            warmup_ratio                = 0.1,
            # CRITICAL: bf16=True, fp16=False for Gemma 4
            bf16                        = True,
            fp16                        = False,
            logging_steps               = 5,
            eval_strategy               = "epoch",
            save_strategy               = "epoch",
            seed                        = RANDOM_SEED,
            report_to                   = "none",
            max_length                  = MAX_SEQ_LENGTH,
            max_prompt_length           = 512,
        ),
    )

    trainer.train()
    elapsed = time.time() - start

    model.save_pretrained(output_dir, safe_serialization=True)
    tokenizer.save_pretrained(output_dir)

    print(f"\n[dpo] DPO complete in {elapsed/60:.1f} min")
    print(f"[dpo] Adapter saved \u2192 {output_dir}")


# ── Entry point ───────────────────────────────────────────────

def run(
    sft_adapter: str,
    eval_path:   str,
    seeds_path:  str,
    output_dir:  str,
    max_pairs:   int = 200,
) -> None:
    dpo_ids   = load_eval_results(eval_path)
    if not dpo_ids:
        print("[dpo] No questions below threshold — DPO not needed. Exiting.")
        return

    seeds     = load_seeds(seeds_path)
    pairs     = build_dpo_pairs(seeds, dpo_ids, max_pairs)

    if not pairs:
        print("[dpo] No DPO pairs built — check seeds and eval results.")
        return

    run_dpo(sft_adapter, pairs, output_dir)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Stage 5b: DPO fine-tuning on weak evaluation questions"
    )
    parser.add_argument("--sft",       required=True,
                        help="Path to SFT adapter (starting point for DPO)")
    parser.add_argument("--eval",      required=True,
                        help="Path to eval results JSON (from eval.py)")
    parser.add_argument("--seeds",     default="data/seeds.jsonl")
    parser.add_argument("--out",       default="outputs/atp-gemma4-31b-dpo",
                        help="Output directory for DPO adapter")
    parser.add_argument("--max-pairs", type=int, default=200,
                        help="Max DPO pairs to generate (default: 200)")
    args = parser.parse_args()
    run(args.sft, args.eval, args.seeds, args.out, args.max_pairs)
